name: Continuous Deployment

# on:
#   release:
#     types: [created]
on: [push]

jobs:
#   Windows:
#     runs-on: windows-latest

#     steps:
#     - uses: actions/checkout@v2
#       with:
#         lfs: true
#         submodules: recursive
    
#     - name: Configure
#       run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      
#     - name: Build
#       run: cmake --build build --config Release

#     - name: Test
#       run: build\liblsdj\test\Release\test.exe
 
  macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      
    - name: Build
      run: cmake --build build --config Release

    - name: Zip
      run: zip liblsdj_macos_${{ github.event.release.tag_name }}.zip ./build/lsdsng_export/lsdsng-export
      run: zip liblsdj_macos_${{ github.event.release.tag_name }}.zip ./build/lsdsng_import/lsdsng-import
      run: zip liblsdj_macos_${{ github.event.release.tag_name }}.zip ./build/lsdj_mono/lsdj-mono
      run: zip liblsdj_macos_${{ github.event.release.tag_name }}.zip ./build/lsdj_wavetable_import/lsdj-wavetable-import
      run: ls -al .
 
#   Ubuntu:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#       with:
#         lfs: true
#         submodules: recursive
    
#     - name: Configure
#       run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      
#     - name: Build
#       run: cmake --build build --config Release

#     - name: Test
#       run: ./build/liblsdj/test/test
