name: Continuous Integration

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    
    - name: configure
      run: mkdir build && cd build && cmake ..
      
    - name: build
      run: cmake --build build

    - name: test
      run: ./build/liblsdj/test/test
