name: Continuous Integration

on: [push, pull_request]

jobs:
  Build Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    
    - name: Configure
      run: mkdir build && cd build && cmake ..
      
    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/liblsdj/test/test
 
  Build macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    
    - name: Configure
      run: mkdir build && cd build && cmake ..
      
    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/liblsdj/test/test
 
  Build Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive
    
    - name: Configure
      run: mkdir build && cd build && cmake ..
      
    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/liblsdj/test/test
